name: Build and Maven

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to maven
        if: contains(github.event.head_commit.message, '[push]') || contains(github.event.head_commit.message, '[build]')
        env:
          SAP_SECRET: ${{ secrets.SAP_SECRET }}
        run: ./gradlew publish
      - uses: actions/upload-artifact@v4
        with:
          name: FabricArtifact
          path: ./fabric/build/libs/*.jar
